sudo: false

os:
- linux

env:
  global:
    - BINSTAR_USER: menpo
  matrix:
    - PYTHON_VERSION: 2.7
    - PYTHON_VERSION: 3.4
    - PYTHON_VERSION: 3.5

install:
- wget https://raw.githubusercontent.com/menpo/condaci/v0.4.6/condaci.py -O condaci.py
- python condaci.py setup

script:
- ~/miniconda/bin/python condaci.py build ./conda

notifications:
  email: false
